name: UpdateAddress Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run IP update script
      run: python cq.py

    - name: Commit 和 push if changed
      run: |
        git config --global user.email "marsgh96@gmail.com"
        git config --global user.name "marsgh0096"
        git add -A
        git commit -m "Automatic IP update" || exit 0
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
      env:
        PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
