name: Run Python Script

on: 
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
       repository: marsgh0096/iptv
       token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: change
      run: |
        git add ip_address.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a || exit 0
        git push https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/marsgh0096/iptv.git

