name: Stock Monitor CI

on:
  workflow_dispatch: # 允许手动触发来测试
  schedule:
    # 使用Cron语法，设置为每5分钟运行一次
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步: 设置Python 3.9 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r py/requirements.txt


      - name: Run Stock Monitor
        env: 
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python py/stock_monitor.py
      

      - name: Commit state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add notified_state.txt
          git commit -m "Update notification state" || true
          git push
