name: Update M3U
on:
  # 触发条件，这里我设置的是每天UTC 00:00触发
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        repository: marsgh0096/iptv
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
    - name: Update M3U
      run: |
        #!/bin/bash
          awk -F 'tvg-name="' '{if($0 ~ /#EXTINF/){split($2, a, "\""); if(!(a[1] in arr)){arr[a[1]]=1; print; getline; gsub("rtp://", "http://192.168.2.1:4022/udp/", $0); print}else{getline}} else if($0 ~ /rtp:/ && !(/#EXTINF/ in arr)){gsub("rtp://", "http://192.168.2.1:4022/udp/", $0); print}}' GuangdongIPTV_rtp_all.m3u > temp && mv temp GuangdongIPTV_rtp_all.m3u
      
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto update
        branch: main
