name: Update M3U
on:
  # 触发条件，这里我设置的是每天UTC 00:00触发
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    
    - name: Update M3U
      run: |
         awk -F ',' '{if(!($2 in arr)){arr[$2]=1; gsub("rtp://", "http://192.168.2.1:4022/udp/", $0); print}}' GuangdongIPTV_rtp_all.m3u > temp && mv temp GuangdongIPTV_rtp_all.m3u
    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Auto update"
        git push
