name: Sync

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00运行
  workflow_dispatch: # 允许手动触发

jobs:
  file_sync:
    runs-on: ubuntu-latest

    steps:
    # 步骤1：检出你的仓库
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: 'main' # 确认你的仓库默认分支是main还是master
      
    # 步骤2：下载文件
    - name: Download file
      run: |
        curl -L https://raw.githubusercontent.com/Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List/master/GuangdongIPTV_rtp_all.m3u -o iptv/gdrtp.m3u
       
    # 步骤3：配置git
    - name: Config git
      run: |
        git config user.email marsgh96@gmail.com
        git config user.name marsgh0096
    
    # 步骤4：提交变更
    - name: Commit & push changes
      run: |
        git add iptv/GuangdongIPTV_rtp_all.m3u
        git commit -m "Sync IPTV list file"
        git push
