name: Sync

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: marsgh0096/iptv
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Sync file
      run: |
        curl -O https://raw.githubusercontent.com/Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List/master/GuangdongIPTV_rtp_all.m3u
        git config --local user.email marsgh96@gmail.com
        git config --local user.name marsgh0096
        git add GuangdongIPTV_rtp_all.m3u
        git commit -m "Sync IPTV list"
        git push
